[package]
name = "rssdown"
version = "0.0.0"
edition = "2021"
description = "Generate an RSS feed from markdown files"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
